name: "CI"
on:
  push:
  pull_request:

jobs:
  build:
    name: Build MATCHI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - run: cargo build --release
        working-directory: ./matchi
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: matchi/target/release/matchi
  release:
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            View CHANGELOG.md for full changes.
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
